# Use the official Node.js image as the base
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the backend source code to the container
COPY bookanytime-backend /app

# Install npm packages
RUN npm install

# Set the command to start the backend server
CMD ["node", "server.js"]

# Expose the port your server is listening on (e.g., 3000)
EXPOSE 5000

